### ISSUE TITLE
Use slugs / ids for routes

### ISSUE THREAD

**Issue by jamesdabbs** [jamesdabbs/pi-base-viewer#10]
Should probably redirect to a standard UID-route but could accept slugs or names where possible.

**Comment by StevenClontz** [comment]
Re-emphasizing that I think UIDs should be the primary mechanism for just about everything we do. My hope is that our UIDs become the standard way to reference spaces/properties/theorems unambiguously.

**Comment by jamesdabbs** [comment]
Oh agreed. Right now we're using `/spaces/Finite%20Discrete%20Topology` and I'm proposing `/spaces/S000001` (which is the only thing we ever link to) _or_ `/spaces/finite-discrete-topology` (for user convenience).

On reflection - I don't think that's actually any more convenient, but the meta-question there is: where do we want to balance standardizing on ids versus user convenience, if there is a conflict between the two? (Ruminating on editing procedures mostly here)
