### ISSUE TITLE
View all traits

### ISSUE THREAD

**Issue by StevenClontz** [jamesdabbs/pi-base-viewer#11]
It would be handy to have a third option on the Space views to view All traits, rather than toggling between Asserted and Deduced.

**Comment by jamesdabbs** [comment]
The buttons aren't toggles any more, though admittedly the UI isn't obvious. Some questions:

* Should this default to showing _all_ traits (with e.g. neither button selected)?
* Should a users toggle selection persist if they move to a new space?

**Comment by StevenClontz** [comment]
Yes - default should definitely be all traits (shouldn't that be both buttons selected?).

The second question could go either way. Do whatever's easier - the ideal UX will become clear once folks have had the chance to use the site actively.

**Comment by jamesdabbs** [comment]
Neither button selected shows all traits anyways (on the assumption that you want to see _something_), and probably feels more natural for your next click (clicking on "Asserted" would show _only_ those, instead of hiding them).

I'll update the default and punt on the other question.

**Comment by StevenClontz** [comment]
sounds good
