### ISSUE TITLE
Show a proof (if possible) when a search fails

### ISSUE THREAD

**Issue by jamesdabbs** [jamesdabbs/pi-base-viewer#15]
If a user searches for T3 + ~T2, they should get a proof demonstrating why that's impossible. (If they run a search that we have no results for, but that we can't rule out, they should see some copy illustrating that.)

**Comment by StevenClontz** [comment]
> No spaces exist satisfying [formula] due to the following theorem: [theorem].

> No spaces found satisfying [formula]. Do you know an example from the literature, or can you provide a reference proving that no such spaces exist? [[Go here to learn how to contribute.]](https://github.com/jamesdabbs/pi-base-data/blob/master/CONTRIBUTING.md)

**Comment by jamesdabbs** [comment]
Initial working version deployed as of cf2ab77977d5aa895a267903365358b45f6a7b11, but still has some edges to work out. See #21
