### ISSUE TITLE
Derive converses where possible

### ISSUE THREAD

**Issue by jamesdabbs** [jamesdabbs/pi-base-viewer#20]
There's enough deduction machinery in place that we shouldn't have to manually tag converses any more.

**Comment by StevenClontz** [comment]
?

Do you mean contrapositives?

**Comment by jamesdabbs** [comment]
Naw, converses. For bi-directional implications like Nagata-Smirnov. The system should be close to smart enough that we don't have to manually point each direction at its converse to have "the converse is also a theorem" show up.

**Comment by StevenClontz** [comment]
Gotcha. Yeah, it'd be especially slick if whenever we have PX→PY and PY→PX then the viewer displays PX←→PY.
