### ISSUE TITLE
Search urls

### ISSUE THREAD

**Issue by jamesdabbs** [jamesdabbs/pi-base-viewer#7]
Search urls should be shareable

**Comment by jamesdabbs** [comment]
This does work now - https://topology.jdabbs.com/spaces?q=compact&text=plank. We could definitely add stuff around bookmarking / saving / sharing searches, but that's a future feature.

**Comment by StevenClontz** [comment]
Fyi erasing the properties textbox on that link leaves CCC as a condition.
Using mobile chrome on Android.

**Comment by jamesdabbs** [comment]
Good catch. That wasn't anything in particular about search URLs, just the "cached the parsed formula" logic. Should be fixed in 58d99a8; should be deployed momentarily.
