### ISSUE TITLE
Markdown / TeX interaction

### ISSUE THREAD

**Issue by jamesdabbs** [jamesdabbs/pi-base-viewer#8]
Underscores and italics are going to be an issue. See: https://pi-base.firebaseapp.com/theorems/I000029

**Comment by StevenClontz** [comment]
I hacked this together once upon a time (and I should make it a proper Ruby gem one day): https://github.com/StevenClontz/deflation It's much easier to deal with \(foo\) than $foo$.

What we probably want is to write an extension for showdown to escape the contents of \(foo\) from all other Markdown parsing: https://github.com/showdownjs/showdown/wiki/extensions

**Comment by jamesdabbs** [comment]
Yeah, it's pretty trivial to control what kind of Math gets rendered ([see]( https://github.com/jamesdabbs/pi-base-viewer/blob/c46c8aeb2e3a7f63e55f97312307e772fda55bd4/public/index.html#L26)), and I'd be happy to standardize on that across the db.

Those extensions look promising; good find.
